import { GoogleTagManager } from '@next/third-parties/google';
import { Roboto } from 'next/font/google';
import './globals.css';
import TopBar from './TopBar';

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <GoogleTagManager gtmId='GTM-N58TR9S' />
      <body className={roboto.className}>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
